// Project/App: gsd-pi
// File Purpose: Publication module — push and draft-PR creation for a merged milestone (ADR-034).
//
// Publication is distinct from the merge verb: merging a milestone branch is a
// Worktree Lifecycle concern (worktree, branch, lease, stash discipline);
// publication needs only the resulting commit, a remote, and preferences.
// Extracted from the tail of `mergeMilestoneToMain` (auto-worktree.ts) so it is
// testable without a merge fixture and reachable from any closeout path.
//
// Publication failure is non-fatal to a completed local merge: every failure is
// logged and reported in the result, never thrown.

import { execFileSync } from "node:child_process";

import {
  buildPullRequestEvidence,
  createDraftPullRequestFromEvidence,
} from "./pull-request-process.js";
import { logWarning } from "./workflow-logger.js";

export interface PublicationPrefs {
  autoPush: boolean;
  autoPr: boolean;
  remote?: string;
  prTargetBranch?: string;
}

export interface PublicationRequest {
  basePath: string;
  milestoneId: string;
  milestoneTitle: string;
  /** The branch the milestone was merged to (push target for auto-push). */
  integrationBranch: string;
  /** The milestone branch (push + PR head for auto-PR). */
  milestoneBranch: string;
  /** Pre-rendered per-slice summary blocks for the PR body. */
  sliceSummaries: readonly string[];
  /** True when the merge found nothing to commit — publication is skipped. */
  nothingToCommit: boolean;
  prefs: PublicationPrefs;
}

export interface PublicationResult {
  pushed: boolean;
  prCreated: boolean;
  prUrl?: string;
}

export function gitRemoteExists(basePath: string, remote: string): boolean {
  try {
    execFileSync("git", ["remote", "get-url", remote], {
      cwd: basePath,
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf-8",
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Publish a merged milestone per preferences: push the integration branch
 * (auto-push, suppressed when auto-PR owns the remote interaction) and/or
 * push the milestone branch and open a draft PR (auto-PR).
 */
export function publishMilestone(request: PublicationRequest): PublicationResult {
  const result: PublicationResult = { pushed: false, prCreated: false };
  if (request.nothingToCommit) return result;

  const { basePath, prefs } = request;
  const remote = prefs.remote ?? "origin";

  if (prefs.autoPush && !prefs.autoPr && gitRemoteExists(basePath, remote)) {
    try {
      execFileSync("git", ["push", remote, request.integrationBranch], {
        cwd: basePath,
        stdio: ["ignore", "pipe", "pipe"],
        encoding: "utf-8",
      });
      result.pushed = true;
    } catch (err) {
      // Push failure is non-fatal
      logWarning("worktree", `git push failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  // #2302: PR creation is not gated on pushed/auto-push.
  if (prefs.autoPr && gitRemoteExists(basePath, remote)) {
    try {
      // Push the milestone branch to remote first
      execFileSync("git", ["push", remote, request.milestoneBranch], {
        cwd: basePath,
        stdio: ["ignore", "pipe", "pipe"],
        encoding: "utf-8",
      });
      const prEvidence = buildPullRequestEvidence({
        milestoneId: request.milestoneId,
        milestoneTitle: request.milestoneTitle,
        changeType: "feat",
        summaries: [...request.sliceSummaries],
        testsRun: ["Auto-created after milestone merge. Run `npm run verify:merge` before marking this draft ready."],
        rollbackNotes: ["Close the draft PR or revert the merge commit if review finds a behavior regression."],
        how: "Generated by git.auto_pr after the milestone branch was pushed and merged locally.",
      });
      const prUrl = createDraftPullRequestFromEvidence(basePath, request.milestoneId, prEvidence, {
        head: request.milestoneBranch,
        base: prefs.prTargetBranch ?? request.integrationBranch,
      });
      if (!prUrl) {
        throw new Error("gh pr create returned no URL");
      }
      result.prCreated = true;
      result.prUrl = prUrl;
    } catch (err) {
      // PR creation failure is non-fatal — gh may not be installed or authenticated
      logWarning("worktree", `PR creation failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return result;
}
